[package]
name = "dbwriter_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

