[package]
name = "dbwriter_rust"
version = "0.1.0"
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["postgres", "chrono", "r2d2"] }
dotenv = "0.15.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4.19"
actix-web = "3"
env_logger = "0.8"

[dev-dependencies]
actix-rt = "1"
