extern crate chrono;
#[macro_use]
extern crate diesel;

use std::env;

use actix_web::{get, post, App, HttpRequest, HttpServer, web};
use chrono::prelude::*;
use diesel::{r2d2, RunQueryDsl};
use diesel::pg::PgConnection;
use diesel::r2d2::ConnectionManager;
use dotenv::dotenv;
use serde::{Deserialize, Serialize};
use schema::sample;

pub mod schema;

type DbPool = r2d2::Pool<ConnectionManager<PgConnection>>;

/*
 * Map structs over the schema in schema.rs that was generated by the database migration.
 * We also mix in a serdes capability so this model serves as the ReST model as well
 */
#[derive(Insertable, Queryable, Serialize, Deserialize, Clone)]
#[table_name = "sample"]
pub struct AddSample<'a> {
    name: &'a str,
    timestamp: NaiveDateTime,
    v0: f32,
    v1: f32,
}

/*
 * Our ReST API
 */
#[get("/")]
async fn hello(req: HttpRequest) -> &'static str {
    "Hello world!"
}

// Returns all the samples in the database
#[get("/samples")]
async fn get_samples(pool: web::Data<DbPool>) -> &'static str {
    "bla"
}

#[get("/samples/{id}")]
async fn get_sample(pool: web::Data<DbPool>, id: web::Path<i32>) -> &'static str {
    "bla"
}

// #[post("/sample")]
// async fn write_samples(pool: web::Data<DbPool>, form: web::Json<AddSample>) -> &'static str {
//     "bla"
// }

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    dotenv().ok();

    // Set up a connection pool to the database
    let db_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");
    let manager = ConnectionManager::<PgConnection>::new(db_url);
    let pool = r2d2::Pool::builder()
        .max_size(12)
        .build(manager)
        .expect(&format!("Error connecting to database"));

    // Put some stuff into our database
    for i in 0..10 {
        let conn = pool.get().unwrap(); // Grab a separate connection for each iteration
        let record = AddSample {
            name: "frobnicator_manifold_pressure",
            timestamp: Utc::now().naive_utc(),
            v0: i as f32,
            v1: (2 * i) as f32,
        };
        let res = diesel::insert_into(sample::dsl::sample)
            .values(record)
            .execute(&conn);
            assert_eq!(res, Ok(1)); // Will be Err(something) if there was a problem
    }
    //let results = sample.ilter

    // Start up the HTTP server, set up the routes and and just block on its completion
    HttpServer::new(move || {  // This is a lambda function with zero arguments
        App::new()
            .data(pool.clone())
            .service(hello)
            .service(get_samples)
            .service(get_sample)
            //.service(write_samples)
    })
    .bind(("127.0.0.1", 8080))?
    .run()
    .await
}
